#-----------------------
#-----------------------
Parameters:
  #-----------------------
  Name:
    Type: String


#-----------------------
#-----------------------
Resources:
  #-----------------------
  Repository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName:
        Ref: Name
