#-----------------------
#-----------------------
Parameters:
  #-----------------------
  Environment:
    Type: String
  #-----------------------
  Name:
    Type: String
  #-----------------------
  SnsTopicArn:
    Type: String
    Default: 'none'
  #-----------------------
  SnsTopic:
    Type: String
    Default: 'none'


#-----------------------
#-----------------------
Resources:
  #-----------------------
  Queue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName:
        Fn::Join:
          - '-'
          - - Ref: Environment
            - Ref: Name
  #-----------------------
  SnsSubscription:
    Type: "AWS::SNS::Subscription"
    Condition: UsingTopic
    Properties:
      Endpoint:
        Fn::GetAtt:
          - 'Queue'
          - 'Arn'
      Protocol: sqs
      TopicArn:
        Fn::If:
          - ThereIsSnsTopicArn
          - Ref: SnsTopicArn
          - Ref:
             Ref: SnsTopic

#-----------------------
#-----------------------
Conditions:
  #-----------------------
  ThereIsSnsTopicArn:
    Fn::Not:
      - Fn::Equals:
          - Ref: SnsTopicArn
          - 'none'
  #-----------------------
  ThereIsSnsTopic:
    Fn::Not:
      - Fn::Equals:
          - Ref: SnsTopic
          - 'none'
  #-----------------------
  UsingTopic:
    Fn::Or:
      - Condition: ThereIsSnsTopicArn
      - Condition: ThereIsSnsTopic